[package]
name = "comptester"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vte = "0.11.0"
ptyprocess = "0.4.1"
anyhow = "1.0.71"

[dev-dependencies]
pretty_assertions = "1.3"
